// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnSQjqxaeVZ5zYIPprUbjy9dt4VAWM47E',
    appId: '1:745464196938:web:9db27e065828cd14cddbb3',
    messagingSenderId: '745464196938',
    projectId: 'fixmyooru',
    authDomain: 'fixmyooru.firebaseapp.com',
    storageBucket: 'fixmyooru.firebasestorage.app',
    measurementId: 'G-EM5BVGZPC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo3AevH1PzYTHXp0og4lasM7XkonXW5bE',
    appId: '1:745464196938:android:3866274a7a58240acddbb3',
    messagingSenderId: '745464196938',
    projectId: 'fixmyooru',
    storageBucket: 'fixmyooru.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH6zO-rXlKKptb0XkQWMlkr7ShtLJhWG4',
    appId: '1:745464196938:ios:a3870f22759144fbcddbb3',
    messagingSenderId: '745464196938',
    projectId: 'fixmyooru',
    storageBucket: 'fixmyooru.firebasestorage.app',
    iosBundleId: 'in.fixmyooru.app.fixmyooru',
  );

}